# Generated by Django 5.1.2 on 2024-11-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('idTag', models.AutoField(primary_key=True, serialize=False)),
                ('libelleTag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('idArt', models.AutoField(primary_key=True, serialize=False)),
                ('imageArt', models.ImageField(upload_to='images/article/')),
                ('titreArt', models.CharField(max_length=100)),
                ('descriptArt', models.TextField()),
                ('dateArt', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.user')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('idCom', models.AutoField(primary_key=True, serialize=False)),
                ('descriptCom', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.user')),
            ],
        ),
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('idDis', models.AutoField(primary_key=True, serialize=False)),
                ('disliked', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('idLike', models.AutoField(primary_key=True, serialize=False)),
                ('liked', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.user')),
            ],
        ),
    ]
